-- MySQL Trigger untuk auto-fill kolom di tabel lhgk

DELIMITER $$

-- Trigger BEFORE INSERT
CREATE TRIGGER lhgk_before_insert 
BEFORE INSERT ON lhgk
FOR EACH ROW
BEGIN
    -- Fill RANGE_GT and RANGE_GT_LABEL
    IF NEW.KP_GRT IS NOT NULL AND (NEW.RANGE_GT IS NULL OR NEW.RANGE_GT = '') THEN
        CASE
            WHEN NEW.KP_GRT BETWEEN 0 AND 3500 THEN
                SET NEW.RANGE_GT = '0-3500 GT', NEW.RANGE_GT_LABEL = 'A';
            WHEN NEW.KP_GRT BETWEEN 3501 AND 8000 THEN
                SET NEW.RANGE_GT = '3501-8000 GT', NEW.RANGE_GT_LABEL = 'B';
            WHEN NEW.KP_GRT BETWEEN 8001 AND 14000 THEN
                SET NEW.RANGE_GT = '8001-14000 GT', NEW.RANGE_GT_LABEL = 'C';
            WHEN NEW.KP_GRT BETWEEN 14001 AND 18000 THEN
                SET NEW.RANGE_GT = '14001-18000 GT', NEW.RANGE_GT_LABEL = 'D';
            WHEN NEW.KP_GRT BETWEEN 18001 AND 26000 THEN
                SET NEW.RANGE_GT = '18001-26000 GT', NEW.RANGE_GT_LABEL = 'E';
            WHEN NEW.KP_GRT BETWEEN 26001 AND 40000 THEN
                SET NEW.RANGE_GT = '26001-40000 GT', NEW.RANGE_GT_LABEL = 'F';
            WHEN NEW.KP_GRT BETWEEN 40001 AND 75000 THEN
                SET NEW.RANGE_GT = '40001-75000 GT', NEW.RANGE_GT_LABEL = 'G';
            WHEN NEW.KP_GRT > 75000 THEN
                SET NEW.RANGE_GT = '>75000 GT', NEW.RANGE_GT_LABEL = 'H';
        END CASE;
    END IF;
    
    -- Fill JENIS_KAPAL_DARI_BENDERA
    IF NEW.KD_BENDERA IS NOT NULL AND (NEW.JENIS_KAPAL_DARI_BENDERA IS NULL OR NEW.JENIS_KAPAL_DARI_BENDERA = '') THEN
        IF UPPER(NEW.KD_BENDERA) IN ('ID', 'IDN', 'INDONESIA') THEN
            SET NEW.JENIS_KAPAL_DARI_BENDERA = 'KAPAL NASIONAL';
        ELSE
            SET NEW.JENIS_KAPAL_DARI_BENDERA = 'KAPAL ASING';
        END IF;
    END IF;
    
    -- Fill TOTAL_PENDAPATAN_PANDU_CLEAN
    IF NEW.PENDAPATAN_PANDU IS NOT NULL AND (NEW.TOTAL_PENDAPATAN_PANDU_CLEAN IS NULL OR NEW.TOTAL_PENDAPATAN_PANDU_CLEAN = 0) THEN
        SET NEW.TOTAL_PENDAPATAN_PANDU_CLEAN = NEW.PENDAPATAN_PANDU;
    END IF;
    
    -- Fill TOTAL_PENDAPATAN_TUNDA_CLEAN
    IF NEW.PENDAPATAN_TUNDA IS NOT NULL AND (NEW.TOTAL_PENDAPATAN_TUNDA_CLEAN IS NULL OR NEW.TOTAL_PENDAPATAN_TUNDA_CLEAN = 0) THEN
        SET NEW.TOTAL_PENDAPATAN_TUNDA_CLEAN = NEW.PENDAPATAN_TUNDA;
    END IF;
END$$

-- Trigger BEFORE UPDATE
CREATE TRIGGER lhgk_before_update 
BEFORE UPDATE ON lhgk
FOR EACH ROW
BEGIN
    -- Fill RANGE_GT and RANGE_GT_LABEL
    IF NEW.KP_GRT IS NOT NULL AND (NEW.RANGE_GT IS NULL OR NEW.RANGE_GT = '') THEN
        CASE
            WHEN NEW.KP_GRT BETWEEN 0 AND 3500 THEN
                SET NEW.RANGE_GT = '0-3500 GT', NEW.RANGE_GT_LABEL = 'A';
            WHEN NEW.KP_GRT BETWEEN 3501 AND 8000 THEN
                SET NEW.RANGE_GT = '3501-8000 GT', NEW.RANGE_GT_LABEL = 'B';
            WHEN NEW.KP_GRT BETWEEN 8001 AND 14000 THEN
                SET NEW.RANGE_GT = '8001-14000 GT', NEW.RANGE_GT_LABEL = 'C';
            WHEN NEW.KP_GRT BETWEEN 14001 AND 18000 THEN
                SET NEW.RANGE_GT = '14001-18000 GT', NEW.RANGE_GT_LABEL = 'D';
            WHEN NEW.KP_GRT BETWEEN 18001 AND 26000 THEN
                SET NEW.RANGE_GT = '18001-26000 GT', NEW.RANGE_GT_LABEL = 'E';
            WHEN NEW.KP_GRT BETWEEN 26001 AND 40000 THEN
                SET NEW.RANGE_GT = '26001-40000 GT', NEW.RANGE_GT_LABEL = 'F';
            WHEN NEW.KP_GRT BETWEEN 40001 AND 75000 THEN
                SET NEW.RANGE_GT = '40001-75000 GT', NEW.RANGE_GT_LABEL = 'G';
            WHEN NEW.KP_GRT > 75000 THEN
                SET NEW.RANGE_GT = '>75000 GT', NEW.RANGE_GT_LABEL = 'H';
        END CASE;
    END IF;
    
    -- Fill JENIS_KAPAL_DARI_BENDERA
    IF NEW.KD_BENDERA IS NOT NULL AND (NEW.JENIS_KAPAL_DARI_BENDERA IS NULL OR NEW.JENIS_KAPAL_DARI_BENDERA = '') THEN
        IF UPPER(NEW.KD_BENDERA) IN ('ID', 'IDN', 'INDONESIA') THEN
            SET NEW.JENIS_KAPAL_DARI_BENDERA = 'KAPAL NASIONAL';
        ELSE
            SET NEW.JENIS_KAPAL_DARI_BENDERA = 'KAPAL ASING';
        END IF;
    END IF;
    
    -- Fill TOTAL_PENDAPATAN_PANDU_CLEAN
    IF NEW.PENDAPATAN_PANDU IS NOT NULL AND (NEW.TOTAL_PENDAPATAN_PANDU_CLEAN IS NULL OR NEW.TOTAL_PENDAPATAN_PANDU_CLEAN = 0) THEN
        SET NEW.TOTAL_PENDAPATAN_PANDU_CLEAN = NEW.PENDAPATAN_PANDU;
    END IF;
    
    -- Fill TOTAL_PENDAPATAN_TUNDA_CLEAN
    IF NEW.PENDAPATAN_TUNDA IS NOT NULL AND (NEW.TOTAL_PENDAPATAN_TUNDA_CLEAN IS NULL OR NEW.TOTAL_PENDAPATAN_TUNDA_CLEAN = 0) THEN
        SET NEW.TOTAL_PENDAPATAN_TUNDA_CLEAN = NEW.PENDAPATAN_TUNDA;
    END IF;
END$$

DELIMITER ;
